### PR TITLE
Selected commits from pull request #82

### PR DESCRIPTION
**Pull request by binnisb**
Selected commits from pr #82 that have to do with the autocompletion.

### CODE REVIEW

**Comment by alneberg** [comment]
Hi @binnisb. I can't get this to work. I tried it on linux and on mac osx with:

concoct --comp<tab> 

but nothing happens. Is that the kind of functionality that this would add or am I not getting it?

**Comment by binnisb** [comment]
What did you do? I can't really remember what I did here, but it should work by doing concoct --comp\t to get suggestions

Have you added the line to bash or have you sourced the autocomplete stuff? It should be printed to terminal when you install concoct

**Comment by binnisb** [comment]
On mac, when installing with python setup.py install:

hanging mode of /Users/binni/.virtualenvs/CONCOCT/bin/concoct to 755

############ Running post install task ##############

####### Will now install bash completion for python scripts
error: No such file or directory

Need to investigate this

**Comment by alneberg** [comment]
Yeah I tried both source and evaluate on both linux and mac. It did make the tab really slow on linux, so it did do something, it just didn't complete with the rest of the option.

**Comment by binnisb** [comment]
I am not sure, I can't get it working now :D Maybe argcomplete has changed, it looks like it needs to define completion in the parser:
http://argcomplete.readthedocs.org/en/latest/

**Comment by alneberg** [comment]
Very strange. Since it slows down (at least mine) shell, I don't think its worth it. I'd say we try to simplify the command line arguments instead.

**Comment by binnisb** [comment]
ok

**Pull request closed without merging**
